apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: vault
          env:
            - name: VAULT_ADDR
              value: https://vault.vault.svc.cluster.local:8200
