apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.23.0
    releaseName: vault
    valuesFile: values.yml
