apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-cop/gitops-catalog//openshift-pipelines-operator/operator/overlays/pipelines-1.9?ref=17c1ef7f1893f6d64a2af9421ce9dfa067feadae
