apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/redhat-cop/gitops-catalog//advanced-cluster-management/operator/overlays/release-2.6?ref=17c1ef7f1893f6d64a2af9421ce9dfa067feadae
  - https://github.com/redhat-cop/gitops-catalog//advanced-cluster-management/instance/base?ref=17c1ef7f1893f6d64a2af9421ce9dfa067feadae
