apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
- helm/
- consolelink.yml
- namespace.yml

patches:
- path: patches/patch-delete-test.yml
- path: patches/patch-service.yml
- path: patches/patch-service-internal.yml
- path: patches/patch-remove-managedby.yml
  target:
    labelSelector: "app.kubernetes.io/managed-by=Helm"
